#include <stdio.h> //printf, scanf, ...
#include <string.h> //memcpy, strlen, ...
#include <unistd.h> //fork, write, sleep...
#include <stdlib.h> //malloc, free, exit...

int		carPosition(unsigned int parkingRow)
{
	return (ffs(parkingRow) - 1);
}

#include "header.h"
