#include <stdio.h> //printf, scanf, ...
#include <string.h> //memcpy, strlen, ...
#include <unistd.h> //fork, write, sleep...
#include <stdlib.h> //malloc, free, exit...

#include "header.h"

unsigned int updatePlace(unsigned int parkingRow, int pos, int value)
{
	return ((parkingRow & (~(0x01 << pos))) | ((value & 1) << pos));
}

